# Generated by Django 2.2.2 on 2019-06-05 17:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id_run', models.AutoField(primary_key=True, serialize=False)),
                ('run_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_time', models.CharField(max_length=200)),
                ('distance', models.FloatField()),
            ],
        ),
    ]
