# Generated by Django 2.2.2 on 2019-06-18 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunSteps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km', models.IntegerField()),
                ('time', models.TimeField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Run')),
            ],
        ),
    ]
